// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShizuAppStoreServer.Core.Data;

#nullable disable

namespace ShizuAppStoreServer.Core.Migrations
{
    [DbContext(typeof(ShizuDbContext))]
    [Migration("20260927200757_AddAppForgeAssetsStale")]
    partial class AddAppForgeAssetsStale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.App", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("ApkLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("apk_label");

                    b.Property<string>("AuthorKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_key");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("author_url");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("availability");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Changelog")
                        .HasColumnType("text")
                        .HasColumnName("changelog");

                    b.Property<string>("ChangelogUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("changelog_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<long?>("DownloadTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("download_total");

                    b.Property<string>("EnrichEtag")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enrich_etag");

                    b.Property<bool>("ExcludeOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_override");

                    b.Property<string>("ExcludedReason")
                        .HasColumnType("text")
                        .HasColumnName("excluded_reason");

                    b.Property<bool>("ForgeAssetsStale")
                        .HasColumnType("boolean")
                        .HasColumnName("forge_assets_stale");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text")
                        .HasColumnName("full_description");

                    b.Property<bool>("HasAds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ads");

                    b.Property<bool>("HasIap")
                        .HasColumnType("boolean")
                        .HasColumnName("has_iap");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("has_paid");

                    b.Property<bool>("IconAdaptive")
                        .HasColumnType("boolean")
                        .HasColumnName("icon_adaptive");

                    b.Property<string>("IconHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("icon_hash");

                    b.Property<long>("InstallCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("install_count");

                    b.Property<DateTimeOffset?>("InstallCountUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("install_count_updated_at");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recommended");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("License")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("license");

                    b.Property<DateTimeOffset?>("ListUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("list_updated_at");

                    b.Property<string>("Listing")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("listing");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PackageName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<bool>("RequiresRoot")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_root");

                    b.Property<long?>("RootAppId")
                        .HasColumnType("bigint")
                        .HasColumnName("root_app_id");

                    b.Property<string>("Screenshots")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("screenshots");

                    b.Property<DateTimeOffset?>("ScreenshotsCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("screenshots_checked_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<int?>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<string>("StoreUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("store_url");

                    b.Property<int?>("TrialDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_days");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<int>("UsageAnalysisVersion")
                        .HasColumnType("integer")
                        .HasColumnName("usage_analysis_version");

                    b.Property<DateTimeOffset?>("UsageAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usage_analyzed_at");

                    b.Property<string>("UsageCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usage_commit");

                    b.Property<string>("UsageMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("usage_markdown");

                    b.Property<string>("UsageMarkdownApiUsage")
                        .HasColumnType("text")
                        .HasColumnName("usage_markdown_api_usage");

                    b.Property<string>("UsageMarkdownNotableDetails")
                        .HasColumnType("text")
                        .HasColumnName("usage_markdown_notable_details");

                    b.Property<string>("UsageMarkdownUsage")
                        .HasColumnType("text")
                        .HasColumnName("usage_markdown_usage");

                    b.Property<string>("UsageModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usage_model");

                    b.Property<int>("UsagePromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("usage_prompt_version");

                    b.Property<string>("UsageReleaseRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("usage_release_ref");

                    b.Property<string>("UsageShort")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("usage_short");

                    b.Property<string>("VersionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version_name");

                    b.Property<DateTimeOffset?>("VersionUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Availability");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RootAppId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Url");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppDownload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abi")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("abi");

                    b.Property<string>("Abis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abis");

                    b.Property<int>("AnalysisVersion")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_version");

                    b.Property<bool>("Analyzed")
                        .HasColumnType("boolean")
                        .HasColumnName("analyzed");

                    b.Property<string>("AnalyzedArtifacts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("analyzed_artifacts");

                    b.Property<string>("ApkUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("apk_url");

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<string>("ArchiveEntry")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("archive_entry");

                    b.Property<int?>("CompileSdk")
                        .HasColumnType("integer")
                        .HasColumnName("compile_sdk");

                    b.Property<bool>("DhizukuDeclared")
                        .HasColumnType("boolean")
                        .HasColumnName("dhizuku_declared");

                    b.Property<bool>("Inspected")
                        .HasColumnType("boolean")
                        .HasColumnName("inspected");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Locales")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locales");

                    b.Property<string>("LocalizedLabels")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localized_labels");

                    b.Property<int?>("MinSdk")
                        .HasColumnType("integer")
                        .HasColumnName("min_sdk");

                    b.Property<string>("PackageName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("package_name");

                    b.Property<string>("ReleaseTag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("release_tag");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Sha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256");

                    b.Property<bool>("ShizukuDeclared")
                        .HasColumnType("boolean")
                        .HasColumnName("shizuku_declared");

                    b.Property<string>("SigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sig_key");

                    b.Property<string>("SigMd5")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sig_md5");

                    b.Property<string>("SigSha256")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sig_sha256");

                    b.Property<string>("SignerDn")
                        .HasColumnType("text")
                        .HasColumnName("signer_dn");

                    b.Property<string>("SignerKeyAlgorithm")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signer_key_algorithm");

                    b.Property<string>("SignerScheme")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signer_scheme");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_ref");

                    b.Property<int?>("TargetSdk")
                        .HasColumnType("integer")
                        .HasColumnName("target_sdk");

                    b.Property<string>("TrackerSignatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracker_signatures");

                    b.Property<string>("TrackerTags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracker_tags");

                    b.Property<string>("Trackers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trackers");

                    b.Property<long?>("VersionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("version_code");

                    b.Property<string>("VersionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version_name");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasFilter("is_primary");

                    b.HasIndex("AppId", "PackageName", "SigKey", "Abi")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("AppId", "PackageName", "SigKey", "Abi"), false);

                    b.ToTable("app_downloads", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppDownloadExclusion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("app_slug");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppSlug", "PackageName")
                        .IsUnique();

                    b.ToTable("app_download_exclusions", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppInstallDay", b =>
                {
                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("InstallCount")
                        .HasColumnType("bigint")
                        .HasColumnName("install_count");

                    b.HasKey("AppId", "Day");

                    b.ToTable("app_install_days", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("apk_url");

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<bool>("IsPrerelease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_prerelease");

                    b.Property<long?>("VersionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("version_code");

                    b.Property<string>("VersionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version_name");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "VersionCode")
                        .IsUnique();

                    b.ToTable("app_versions", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppVersionInstallDay", b =>
                {
                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<long>("VersionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("version_code");

                    b.Property<string>("InstallType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("install_type");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("InstallCount")
                        .HasColumnType("bigint")
                        .HasColumnName("install_count");

                    b.HasKey("AppId", "VersionCode", "InstallType", "Day");

                    b.ToTable("app_version_install_days", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("section");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Section", "ParentId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.ClientUserAgent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("LastPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_path");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint")
                        .HasColumnName("request_count");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("UserAgent")
                        .IsUnique();

                    b.ToTable("client_user_agents", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.ClientUserAgentDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint")
                        .HasColumnName("request_count");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("UserAgent", "Day")
                        .IsUnique();

                    b.ToTable("client_user_agent_days", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.ConfigFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config_flags", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.JobEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Phase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phase");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("JobRunId", "Seq")
                        .IsUnique();

                    b.HasIndex("JobRunId", "Type");

                    b.ToTable("job_events", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.JobRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("EventsCount")
                        .HasColumnType("integer")
                        .HasColumnName("events_count");

                    b.Property<int>("EventsDropped")
                        .HasColumnType("integer")
                        .HasColumnName("events_dropped");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("items_failed");

                    b.Property<int>("ItemsOk")
                        .HasColumnType("integer")
                        .HasColumnName("items_ok");

                    b.Property<int>("ItemsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("items_skipped");

                    b.Property<int>("ItemsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("items_total");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateOnly>("StartedDay")
                        .HasColumnType("date")
                        .HasColumnName("started_day");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.Property<long?>("UsageAnalysisRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("usage_analysis_run_id");

                    b.HasKey("Id");

                    b.HasIndex("StartedDay");

                    b.HasIndex("UsageAnalysisRunId");

                    b.HasIndex("Kind", "StartedDay");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.PackageException", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PackageName")
                        .IsUnique();

                    b.ToTable("package_exceptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "Allow",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Note = "Uses the rish shell gateway instead of the Shizuku permission.",
                            PackageName = "kr.scin.rishmcp",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.RemovedApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Listing")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("listing");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("RemovedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("removed_apps", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.RequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CfRay")
                        .HasColumnType("text")
                        .HasColumnName("cf_ray");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ForwardedFor")
                        .HasColumnType("text")
                        .HasColumnName("forwarded_for");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("Host")
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("QueryString")
                        .HasColumnType("text")
                        .HasColumnName("query_string");

                    b.Property<string>("RawRequest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_request");

                    b.Property<string>("RawTarget")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_target");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("text")
                        .HasColumnName("remote_ip");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheme");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("SeenAt");

                    b.ToTable("request_logs", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.SyncIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("JobRunId");

                    b.HasIndex("Kind");

                    b.HasIndex("Rule");

                    b.HasIndex("Slug");

                    b.ToTable("sync_issues", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.SyncRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Full")
                        .HasColumnType("boolean")
                        .HasColumnName("full");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.ToTable("sync_requests", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.UsageAnalysisRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("CachedInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cached_input_tokens");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("LogFile")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("log_file");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RepoCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("repo_commit");

                    b.Property<string>("RepoForge")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("repo_forge");

                    b.Property<string>("RepoRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repo_ref");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("ToolCalls")
                        .HasColumnType("integer")
                        .HasColumnName("tool_calls");

                    b.Property<string>("Trigger")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasFilter("status in ('Pending', 'Running')");

                    b.HasIndex("AppId", "CreatedAt");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("usage_analysis_runs", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.App", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.Category", "Category")
                        .WithMany("Apps")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "Root")
                        .WithMany("Variants")
                        .HasForeignKey("RootAppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Parent");

                    b.Navigation("Root");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppDownload", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany("Downloads")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppInstallDay", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppVersion", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany("Versions")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppVersionInstallDay", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.Category", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.JobEvent", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShizuAppStoreServer.Core.Data.JobRun", "JobRun")
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.JobRun", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.UsageAnalysisRun", "UsageAnalysisRun")
                        .WithMany()
                        .HasForeignKey("UsageAnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsageAnalysisRun");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.SyncIssue", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShizuAppStoreServer.Core.Data.JobRun", "JobRun")
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.UsageAnalysisRun", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.App", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Downloads");

                    b.Navigation("Variants");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.Category", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
