// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShizuAppStoreServer.Core.Data;

#nullable disable

namespace ShizuAppStoreServer.Core.Migrations
{
    [DbContext(typeof(ShizuDbContext))]
    [Migration("20260913141903_AddAppVersionUpdatedAt")]
    partial class AddAppVersionUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.App", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("availability");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("DownloadTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("download_total");

                    b.Property<string>("EnrichEtag")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enrich_etag");

                    b.Property<bool>("ExcludeOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_override");

                    b.Property<string>("ExcludedReason")
                        .HasColumnType("text")
                        .HasColumnName("excluded_reason");

                    b.Property<bool>("HasAds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ads");

                    b.Property<bool>("HasIap")
                        .HasColumnType("boolean")
                        .HasColumnName("has_iap");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("has_paid");

                    b.Property<bool>("IconAdaptive")
                        .HasColumnType("boolean")
                        .HasColumnName("icon_adaptive");

                    b.Property<string>("IconHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("icon_hash");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recommended");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("License")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("license");

                    b.Property<string>("Listing")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("listing");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PackageName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<bool>("RequiresRoot")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_root");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<int?>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<string>("StoreUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("store_url");

                    b.Property<int?>("TrialDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_days");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<DateTimeOffset?>("VersionUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Availability");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Url");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppDownload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApkUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("apk_url");

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<string>("ArchiveEntry")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("archive_entry");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int?>("MinSdk")
                        .HasColumnType("integer")
                        .HasColumnName("min_sdk");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Sha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256");

                    b.Property<string>("SigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sig_key");

                    b.Property<string>("SigMd5")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sig_md5");

                    b.Property<string>("SigSha256")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sig_sha256");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_ref");

                    b.Property<long?>("VersionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("version_code");

                    b.Property<string>("VersionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version_name");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasFilter("is_primary");

                    b.HasIndex("AppId", "SigKey")
                        .IsUnique();

                    b.ToTable("app_downloads", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("apk_url");

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<long?>("VersionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("version_code");

                    b.Property<string>("VersionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version_name");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "VersionCode")
                        .IsUnique();

                    b.ToTable("app_versions", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("section");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Section", "ParentId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.RemovedApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Listing")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("listing");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("RemovedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("removed_apps", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.SyncRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.ToTable("sync_requests", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.SyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Added")
                        .HasColumnType("integer")
                        .HasColumnName("added");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("HeadCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("head_commit");

                    b.Property<int>("Removed")
                        .HasColumnType("integer")
                        .HasColumnName("removed");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.App", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.Category", "Category")
                        .WithMany("Apps")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppDownload", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany("Downloads")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.AppVersion", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.App", "App")
                        .WithMany("Versions")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.Category", b =>
                {
                    b.HasOne("ShizuAppStoreServer.Core.Data.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.App", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Downloads");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ShizuAppStoreServer.Core.Data.Category", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
